### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mukkachaitanya** [yan-foto/electron-reload#15]
I am getting the following error while trying to use the module.

```
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\path\Electron\music-player\node_modules\electron\dist\resources\electron.as
ar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\path\Electron\music-player\node_modules\electron-reload\main.js:1:90)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

And the `main.js` has the following for usage of the module 
```js
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
require('electron-reload')(__dirname+'/public')
```

Can anyone guide me how to resolve the problem ?

**Comment by yan-foto** [comment]
Please consult stackoverflow or similar. The issues are only for bugs/enhancements.
