### ISSUE TITLE
Error loading the moduel

### ISSUE THREAD

**Issue by evanlarkin10** [yan-foto/electron-reload#92]
**NOTE**: before openning an issue, please consult previous issues (both open and closed).

## What is the problem
if (env === "development") {
  try {
    require("electron-reload")(__dirname);
  } catch (e) {
    console.log(e);
  }
}

This throws the error:

const options = {type: EV_ALL, alwaysStat: true, lstat: true, ...opts};                                                          
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/elarkin/Documents/python-electron/node_modules/electron-reload/main.js:2:18)

Any idea why it doesn't like the spread operator?
Node v14.13.0

package.json
 "devDependencies": {
    "electron": "^1.8.8",
    "electron-reload": "^1.5.0",
}

**Comment by yan-foto** [comment]
Sorry @evanlarkin10 but I have to close the issue: I don't see any `electron-reload` files in your copied stacktrace!
